# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='资产编码')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('category', models.CharField(max_length=50, verbose_name='资产类别')),
                ('status', models.IntegerField(choices=[(1, '使用中'), (2, '闲置'), (3, '维修中'), (4, '已报废')], default=1, verbose_name='状态')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购置日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='购置价格')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'asset',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='托盘编号')),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大承重(kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='可用')),
            ],
            options={
                'verbose_name': '托盘',
                'verbose_name_plural': '托盘',
                'db_table': 'pallet',
            },
        ),
    ]
