# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当前数量')),
                ('locked_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='锁定数量')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('movement_type', models.IntegerField(choices=[(1, '入库'), (2, '出库'), (3, '移库'), (4, '盘点调整'), (5, '报损')], verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动数量')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联单号')),
                ('ref_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='关联单据类型')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'stock_movement',
                'ordering': ['-created_at'],
            },
        ),
    ]
