# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='from_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='warehouse.bin', verbose_name='源库位'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='goods.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='warehouse.bin', verbose_name='目标库位'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='stock',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.bin', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='stock',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='goods.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['goods', '-created_at'], name='stock_movem_goods_i_11782e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', '-created_at'], name='stock_movem_warehou_19e60f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ref_no'], name='stock_movem_ref_no_5d5781_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['goods', 'warehouse'], name='stock_goods_i_265f50_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse', 'bin'], name='stock_warehou_98fc2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('goods', 'warehouse', 'bin')},
        ),
    ]
