# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asn_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '已到货'), (3, '已卸货'), (4, '已上架')], default=1, verbose_name='状态')),
                ('expected_time', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='实际入库时间')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总数量')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'asn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实收数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asn.asn', verbose_name='入库单')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asn_items', to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '入库明细',
                'verbose_name_plural': '入库明细',
                'db_table': 'asn_item',
                'ordering': ['created_at'],
            },
        ),
    ]
