# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('asn', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asnitem',
            name='target_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asn_items', to='warehouse.bin', verbose_name='目标库位'),
        ),
        migrations.AddField(
            model_name='asn',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_asns', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='asn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asns', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='asn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asns', to='warehouse.warehouse', verbose_name='目标仓库'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['asn_no'], name='asn_asn_no_1c08a0_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['status'], name='asn_status_aa18fc_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['supplier', '-created_at'], name='asn_supplie_2dbadc_idx'),
        ),
    ]
