# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='仓库编码')),
                ('address', models.TextField(blank=True, null=True, verbose_name='仓库地址')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='面积(㎡)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='库区名称')),
                ('code', models.CharField(max_length=30, verbose_name='库区编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库区',
                'verbose_name_plural': '库区',
                'db_table': 'warehouse_zone',
                'ordering': ['sort'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=30, verbose_name='库位编码')),
                ('row', models.CharField(blank=True, max_length=10, null=True, verbose_name='排')),
                ('col', models.CharField(blank=True, max_length=10, null=True, verbose_name='列')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='层')),
                ('attribute', models.CharField(choices=[('N', '正常'), ('D', '损坏'), ('H', '暂存'), ('I', '检验')], default='N', max_length=1, verbose_name='库位属性')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='长(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='宽(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='高(cm)')),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最大容量')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehouse.warehouse', verbose_name='所属仓库')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='warehouse.zone', verbose_name='所属库区')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
                'db_table': 'warehouse_bin',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
    ]
