# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='系统数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='实盘数量')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='差异')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'db_table': 'count_record',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('count_no', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '盘点中'), (3, '已完成'), (4, '已调整')], default=1, verbose_name='状态')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划盘点日期')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '盘点单',
                'verbose_name_plural': '盘点单',
                'db_table': 'cycle_count',
                'ordering': ['-created_at'],
            },
        ),
    ]
