# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cyclecount', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecount',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to='warehouse.warehouse', verbose_name='盘点仓库'),
        ),
        migrations.AddField(
            model_name='countrecord',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_records', to='warehouse.bin', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='countrecord',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_records', to=settings.AUTH_USER_MODEL, verbose_name='盘点人'),
        ),
        migrations.AddField(
            model_name='countrecord',
            name='cycle_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cyclecount.cyclecount', verbose_name='盘点单'),
        ),
        migrations.AddField(
            model_name='countrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_records', to='goods.goods', verbose_name='商品'),
        ),
    ]
