# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dn_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '已确认'), (3, '已拣货'), (4, '已发货')], default=1, verbose_name='状态')),
                ('expected_time', models.DateTimeField(blank=True, null=True, verbose_name='预计发货时间')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='实际发货时间')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总数量')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='收货地址')),
                ('tracking_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'dn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实发数量')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '出库明细',
                'verbose_name_plural': '出库明细',
                'db_table': 'dn_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(1, '待拣货'), (2, '拣货中'), (3, '已完成')], default=1, verbose_name='状态')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_lists', to='dn.dn', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '拣货单',
                'verbose_name_plural': '拣货单',
                'db_table': 'picking_list',
                'ordering': ['-created_at'],
            },
        ),
    ]
