# Generated by Django 4.2.30 on 2026-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('dn', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglist',
            name='picker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picking_lists', to=settings.AUTH_USER_MODEL, verbose_name='拣货人'),
        ),
        migrations.AddField(
            model_name='dnitem',
            name='dn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dn.dn', verbose_name='出库单'),
        ),
        migrations.AddField(
            model_name='dnitem',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dn_items', to='goods.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='dnitem',
            name='source_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dn_items', to='warehouse.bin', verbose_name='拣货库位'),
        ),
        migrations.AddField(
            model_name='dn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dns', to='customer.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='dn',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dns', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='dn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dns', to='warehouse.warehouse', verbose_name='出库仓库'),
        ),
        migrations.AddIndex(
            model_name='dn',
            index=models.Index(fields=['dn_no'], name='dn_dn_no_f48313_idx'),
        ),
        migrations.AddIndex(
            model_name='dn',
            index=models.Index(fields=['status'], name='dn_status_c236a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dn',
            index=models.Index(fields=['customer', '-created_at'], name='dn_custome_c966d1_idx'),
        ),
    ]
